<a href="https://colab.research.google.com/github/gowrignair306-boop/Machine-learning-project/blob/main/Day_2_NumPy_and_Pndas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [43]:
#load dataset
df=sns.load_dataset("titanic")

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [45]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [46]:
df.shape

(891, 15)

In [47]:
df.size

13365

In [48]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [49]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [50]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [51]:
#checking missing values
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [52]:
df.shape

(891, 15)

In [53]:
df_clean=df.drop(columns=['deck'])
df_clean #column remove

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [54]:
#null values inside the column
df.dropna(subset=['embarked','embark_town'],inplace=True)
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [55]:
#filling numerical values with mean
age_mean=df['age'].mean()
df['age']=df['age'].fillna(age_mean)

In [56]:
#create a column family_size:
df['family_size']=df['sibsp']+df['parch']
#create age_group column:
df['age_group']=np.where(df['age']<18,"Child","Adult")

In [57]:
#create column fare_per_person
df['fare_per_person']=df['fare']/(df['family_size']+1)

In [58]:
df.rename(columns={'pclass':'Passenger_class'},inplace=True)
df

,survived,Passenger_class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size,age_group,fare_per_person
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,Adult,3.62500
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,Adult,35.64165
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0,Adult,7.92500
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,Adult,26.55000
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0,Adult,8.05000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,0,Adult,13.00000
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0,Adult,30.00000
888,0,3,female,29.642093,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,3,Adult,5.86250
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,0,Adult,30.00000
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0,Adult,7.75000

In [59]:
#Passengers older than average age
df[df['age']>df['age'].mean()]

,survived,Passenger_class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size,age_group,fare_per_person
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,Adult,35.641650
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,Adult,26.550000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0,Adult,8.050000
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,0,Adult,51.862500
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,0,Adult,26.550000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True,0,Adult,9.000000
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,1,Adult,41.579150
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,0,Adult,7.895800
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False,5,Adult,4.854167
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0,Adult,7.750000

In [60]:
#Female passengers in first class
df[(df['sex']=='female')& (df['Passenger_class']==1)]

,survived,Passenger_class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size,age_group,fare_per_person
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,Adult,35.641650
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,Adult,26.550000
11,1,1,female,58.000000,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,0,Adult,26.550000
31,1,1,female,29.642093,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False,1,Adult,73.260400
52,1,1,female,49.000000,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False,1,Adult,38.364600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.000000,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False,2,Adult,54.955567
862,1,1,female,48.000000,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True,0,Adult,25.929200
871,1,1,female,47.000000,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False,2,Adult,17.518067
879,1,1,female,56.000000,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,1,Adult,41.579150
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0,Adult,30.000000

In [12]:
df1=sns.load_dataset("penguins")

In [13]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [14]:
df1.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [15]:
df1.shape

(344, 7)

In [16]:
df1.size

2408

In [17]:
df1.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [18]:
df1.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [19]:
#checking missing values
df1.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [21]:
#null values inside the column
df1.dropna(subset=['bill_length_mm','flipper_length_mm'],inplace=True)
df1

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [25]:
#filling numerical values with mean
bill_length_mean=df['bill_length_mm'].mean()
df['bill_length_mm']=df['bill_length_mm'].fillna(bill_length_mean)
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10000,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.50000,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.30000,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,43.92193,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.70000,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,43.92193,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.80000,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.40000,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.20000,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.90000,16.1,213.0,5400.0,Male

In [27]:
bill_depth_mean=df['bill_depth_mm'].mean()
df['bill_depth_mm']=df['bill_depth_mm'].fillna(bill_depth_mean)
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10000,18.70000,181.0,3750.0,Male
1,Adelie,Torgersen,39.50000,17.40000,186.0,3800.0,Female
2,Adelie,Torgersen,40.30000,18.00000,195.0,3250.0,Female
3,Adelie,Torgersen,43.92193,17.15117,NaN,NaN,NaN
4,Adelie,Torgersen,36.70000,19.30000,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,43.92193,17.15117,NaN,NaN,NaN
340,Gentoo,Biscoe,46.80000,14.30000,215.0,4850.0,Female
341,Gentoo,Biscoe,50.40000,15.70000,222.0,5750.0,Male
342,Gentoo,Biscoe,45.20000,14.80000,212.0,5200.0,Female
343,Gentoo,Biscoe,49.90000,16.10000,213.0,5400.0,Male

In [28]:
#filling the numeric value using median
bill_length_median=df['bill_length_mm'].median()
df['bill_length_mm']=df['bill_length_mm'].fillna(bill_length_median)
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10000,18.70000,181.0,3750.0,Male
1,Adelie,Torgersen,39.50000,17.40000,186.0,3800.0,Female
2,Adelie,Torgersen,40.30000,18.00000,195.0,3250.0,Female
3,Adelie,Torgersen,43.92193,17.15117,NaN,NaN,NaN
4,Adelie,Torgersen,36.70000,19.30000,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,43.92193,17.15117,NaN,NaN,NaN
340,Gentoo,Biscoe,46.80000,14.30000,215.0,4850.0,Female
341,Gentoo,Biscoe,50.40000,15.70000,222.0,5750.0,Male
342,Gentoo,Biscoe,45.20000,14.80000,212.0,5200.0,Female
343,Gentoo,Biscoe,49.90000,16.10000,213.0,5400.0,Male

In [30]:
df1['bill_ratio']=df1['bill_length_mm']/df1['bill_depth_mm']
df1

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767
...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,3.445255
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,3.272727
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,3.210191
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,3.054054
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,3.099379

In [31]:
df1.rename(columns={'bill_length_mm':'bill_length'},inplace=True)
df1

,species,island,bill_length,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767
...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,3.445255
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,3.272727
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,3.210191
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,3.054054
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,3.099379

In [32]:
df1['body_mass_g']>df1['body_mass_g'].mean()

0      False
1      False
2      False
4      False
5      False
       ...
338     True
340     True
341     True
342     True
343     True
Name: body_mass_g, Length: 342, dtype: bool

In [36]:
df1[(df1['sex']=='Female')&(df1['flipper_length_mm']>200)]

,species,island,bill_length,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio
90,Adelie,Dream,35.7,18.0,202.0,3550.0,Female,1.983333
216,Chinstrap,Dream,43.5,18.1,202.0,3400.0,Female,2.403315
220,Gentoo,Biscoe,46.1,13.2,211.0,4500.0,Female,3.492424
222,Gentoo,Biscoe,48.7,14.1,210.0,4450.0,Female,3.453901
225,Gentoo,Biscoe,46.5,13.5,210.0,4550.0,Female,3.444444
226,Gentoo,Biscoe,45.4,14.6,211.0,4800.0,Female,3.109589
228,Gentoo,Biscoe,43.3,13.4,209.0,4400.0,Female,3.231343
230,Gentoo,Biscoe,40.9,13.7,214.0,4650.0,Female,2.985401
232,Gentoo,Biscoe,45.5,13.7,214.0,4650.0,Female,3.321168
234,Gentoo,Biscoe,45.8,14.6,210.0,4200.0,Female,3.136986
236,Gentoo,Biscoe,42.0,13.5,210.0,4150.0,Female,3.111111
238,Gentoo,Biscoe,46.2,14.5,209.0,4800.0,Female,3.186207
241,Gentoo,Biscoe,45.1,14.5,215.0,5000.0,Female,3.110345
242,Gentoo,Biscoe,46.5,14.5,213.0,4400.0,Female,3.206897
244,Gentoo,Biscoe,42.9,13.1,215.0,5000.0,Female,3.274809
248,Gentoo,Biscoe,48.2,14.3,210.0,4600.0,Female,3.370629
251,Gentoo,Biscoe,42.8,14.2,209.0,4700.0,Female,3.014085
252,Gentoo,Biscoe,45.1,14.5,207.0,5050.0,Female,3.110345
254,Gentoo,Biscoe,49.1,14.8,220.0,5150.0,Female,3.317568
256,Gentoo,Biscoe,42.6,13.7,213.0,4950.0,Female,3.109489
258,Gentoo,Biscoe,44.0,13.6,208.0,4350.0,Female,3.235294
260,Gentoo,Biscoe,42.7,13.7,208.0,3950.0,Female,3.116788
262,Gentoo,Biscoe,45.3,13.7,210.0,4300.0,Female,3.306569
265,Gentoo,Biscoe,43.6,13.9,217.0,4900.0,Female,3.136691
266,Gentoo,Biscoe,45.5,13.9,210.0,4200.0,Female,3.273381
268,Gentoo,Biscoe,44.9,13.3,213.0,5100.0,Female,3.375940
270,Gentoo,Biscoe,46.6,14.2,210.0,4850.0,Female,3.281690
272,Gentoo,Biscoe,45.1,14.4,210.0,4400.0,Female,3.131944
274,Gentoo,Biscoe,46.5,14.4,217.0,4900.0,Female,3.229167
276,Gentoo,Biscoe,43.8,13.9,208.0,4300.0,Female,3.151079
278,Gentoo,Biscoe,43.2,14.5,208.0,4450.0,Female,2.979310
280,Gentoo,Biscoe,45.3,13.8,208.0,4200.0,Female,3.282609
282,Gentoo,Biscoe,45.7,13.9,214.0,4400.0,Female,3.287770
284,Gentoo,Biscoe,45.8,14.2,219.0,4700.0,Female,3.225352
288,Gentoo,Biscoe,43.5,14.2,220.0,4700.0,Female,3.063380
290,Gentoo,Biscoe,47.7,15.0,216.0,4750.0,Female,3.180000
293,Gentoo,Biscoe,46.5,14.8,217.0,5200.0,Female,3.141892
294,Gentoo,Biscoe,46.4,15.0,216.0,4700.0,Female,3.093333
296,Gentoo,Biscoe,47.5,14.2,209.0,4600.0,Female,3.345070
298,Gentoo,Biscoe,45.2,13.8,215.0,4750.0,Female,3.275362
300,Gentoo,Biscoe,49.1,14.5,212.0,4625.0,Female,3.386207
302,Gentoo,Biscoe,47.4,14.6,212.0,4725.0,Female,3.246575
304,Gentoo,Biscoe,44.9,13.8,212.0,4750.0,Female,3.253623
306,Gentoo,Biscoe,43.4,14.4,218.0,4600.0,Female,3.013889
308,Gentoo,Biscoe,47.5,14.0,212.0,4875.0,Female,3.392857
310,Gentoo,Biscoe,47.5,15.0,218.0,4950.0,Female,3.166667
312,Gentoo,Biscoe,45.5,14.5,212.0,4750.0,Female,3.137931
314,Gentoo,Biscoe,44.5,14.7,214.0,4850.0,Female,3.027211
317,Gentoo,Biscoe,46.9,14.6,222.0,4875.0,Female,3.212329
318,Gentoo,Biscoe,48.4,14.4,203.0,4625.0,Female,3.361111
320,Gentoo,Biscoe,48.5,15.0,219.0,4850.0,Female,3.233333
322,Gentoo,Biscoe,47.2,15.5,215.0,4975.0,Female,3.045161
326,Gentoo,Biscoe,41.7,14.7,210.0,4700.0,Female,2.836735
328,Gentoo,Biscoe,43.3,14.0,208.0,4575.0,Female,3.092857
330,Gentoo,Biscoe,50.5,15.2,216.0,5000.0,Female,3.322368
332,Gentoo,Biscoe,43.5,15.2,213.0,4650.0,Female,2.861842
334,Gentoo,Biscoe,46.2,14.1,217.0,4375.0,Female,3.276596
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,3.445255
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,3.272727
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,3.054054

In [38]:
df1.groupby('sex')['bill_ratio'].mean()

sex
Female    2.609508
Male      2.604988
Name: bill_ratio, dtype: float64

In [40]:
df1.groupby('species')['flipper_length_mm'].mean()

species
Adelie       189.953642
Chinstrap    195.823529
Gentoo       217.186992
Name: flipper_length_mm, dtype: float64

In [41]:
df1.corr(numeric_only=True)

,bill_length,bill_depth_mm,flipper_length_mm,body_mass_g,bill_ratio
bill_length,1.000000,-0.235053,0.656181,0.595110,0.780396
bill_depth_mm,-0.235053,1.000000,-0.583851,-0.471916,-0.784191
flipper_length_mm,0.656181,-0.583851,1.000000,0.871202,0.805166
body_mass_g,0.595110,-0.471916,0.871202,1.000000,0.703119
bill_ratio,0.780396,-0.784191,0.805166,0.703119,1.000000